import type { Metadata } from "next"
import "./globals.css"
import { MSWComponent } from "@/mock/MSWComponent"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <MSWComponent />
      <body>{children}</body>
    </html>
  )
}
