name: EC2 Depolyment Update

on:
  pull_request:
    types: [closed]
    branches:
      - released

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/Network-office-FE
            git fetch
            git checkout released
            git pull origin released
            pnpm i
            pnpm run build
            pm2 restart Network-office-FE
