name: Run Unit Test & E2E Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: write-all

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm store
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Jest tests
        run: pnpm test -- --coverage --passWithNoTests
        continue-on-error: true

      - name: Save coverage report
        run: mv coverage/lcov-report ./coverage-output

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "./test-results/junit/results.xml"
          check_name: "Jest Test Results"
          comment_mode: always

  cypress-test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Cypress tests
        run: pnpm run e2e:ci
        env:
          CYPRESS_BASE_URL: http://localhost:3000
